### ISSUE TITLE
Django 2.x support?

### ISSUE THREAD

**Issue by mawkee** [peterbe/django-cache-memoize#14]
Are there plans for adding support for Django 2.x?

**Comment by peterbe** [comment]
Does it not already support Django 2.x?

See https://github.com/peterbe/django-cache-memoize/blob/062c71066bd721970406cc07aa7fc3f73ee21f72/tox.ini#L10-L11

Close?

**Comment by mawkee** [comment]
Yeah, missed those; I was looking at the `README.rst`

**Comment by peterbe** [comment]
Then the README definitely needs to be updated. Care to send a PR? Something that matches the tox.ini. Actually, the best thing would be if it could link to the tox.ini file.

**Comment by mawkee** [comment]
Sure

**Comment by peterbe** [comment]
https://github.com/peterbe/django-cache-memoize/commit/4ca78b76bca4eca53b9a65618a059bcb2c99f00b
