### ISSUE TITLE
Drop python 2.7 support

### ISSUE THREAD

**Issue by Geekfish** [peterbe/django-cache-memoize#25]
Related to discussions on how to implement #15 and [pending python2.7 "end-of-life"][1] in about a year, it's probably a good time to try to drop support and open up to python3-only features without the headache of maintaining compatibility.

Maybe a good chance to add version `3.7` to the tox config too, as [it now seems to be available on Travis][2]

[1]: https://devguide.python.org/#status-of-python-branches
[2]: https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905

**Comment by Geekfish** [comment]
Another kind of relevant thing:
https://www.djangoproject.com/download/#supported-versions

Django < 1.11 is now not officially supported anymore. But at the same time nothing seems to have changed so far that requires special handling for backwards compat, so maybe just a thing to have in mind if this **does** happen in the future.

**Comment by ntoll** [comment]
I'm with Eleni/@geekfish ... +1 for dropping 2.7.

**Comment by hugovk** [comment]
Please see PR #26 to drop Python 2.7 and add 3.7.

Please see PR #27 to also drop EOL Django versions.
