### ISSUE TITLE
How to know the cache key of a cached function?

### ISSUE THREAD

**Issue by aj07mm** [peterbe/django-cache-memoize#34]
How to know the cache key of a cached function?

**Comment by peterbe** [comment]
Reading the source code :)

Seriously, there is no API for that. But it would be cool. Just like the wrapped function `.invalidate` "method" there could be some called `.get_cache_key`.

What's your use case?

**Comment by aj07mm** [comment]
I want to check that the cache key exists before running the cached function. My cached function takes a lot of time.

**Comment by peterbe** [comment]
Just like there's a `invalidate` method, I think you should add a PR that does something similar but returns the cache key string.
