### ISSUE TITLE
Does invalidate() return the new cached result?

### ISSUE THREAD

**Issue by mbi** [peterbe/django-cache-memoize#4]
Your README seems to imply that the `invalidate()` call doesn't return the new value:

    >>> expensive_function(100, 200)
    121
    >>> exensive_function.invalidate(1, 200)
    >>> expensive_function(1, 100)
    89

… however a call with `_refresh=True` does:

    >>> expensive_function(100, 200)
    121
    >>> expensive_function(100, 200, _refresh=True)
    177
    >>> expensive_function(100, 200)
    177

Is this correct?

**Comment by peterbe** [comment]
Correct understanding. The [`invalidate` function](https://github.com/peterbe/django-cache-memoize/blob/8c8091d2cfc916877a559365352dbf5c73750d30/src/cache_memoize/__init__.py#L117-L119) doesn't actually run the function you're decoratoring.

Clearly this wasn't clear from the documentation (hence you filing this issue). 
Can you suggest a docs update to make it more clear?

**Comment by mbi** [comment]
Nah, it's fine: I think it's clear enough as it is in the current README.
