### ISSUE TITLE
Release the package with Django 3.2 support

### ISSUE THREAD

**Issue by Jawayria** [peterbe/django-cache-memoize#52]
Hey, we are working on upgrading edX codebase to Django 3.2. This package is being used in the codebase but it isn't yet released with Django 3.2 support. Kindly consider releasing it with Django 3.2 support.
Thanks

**Comment by peterbe** [comment]
@Jawayria Thanks for reminding me!
https://github.com/peterbe/django-cache-memoize/pull/53

**Comment by peterbe** [comment]
Should be up now: https://pypi.org/project/django-cache-memoize/0.1.10/
