### ISSUE TITLE
Cache miss each time if used on class instance method

### ISSUE THREAD

**Issue by darklow** [peterbe/django-cache-memoize#8]
Looks like ``self`` param is being taken into account.
Current workaround that works is using empty `args_rewrite` list:
```py
class MyClass(object):

    @cache_memoize(30, args_rewrite=lambda x: [])
    def get_data(self):
      #....
```

**Comment by poleha** [comment]
That's not issue but expected behavior.
I see at least two correct ways to handle this situation:

```
@cache_memoize(30, args_rewrite=lambda self, *args: args)
def get_data(self):
    pass
```

or

```
from django.utils.decorators import method_decorator


@method_decorator(cache_memoize(30, prefix='get_data'))
def get_data(self):
    pass
```

**Comment by peterbe** [comment]
+1 on `method_decorator`

**Comment by matt-dalton** [comment]
The only downside with this is that you then can't use the hot cache pattern. e.g. 
```
MyClass.get_data(MyClass, refresh=True)
```
gives `get_data() takes 1 positional argument but 2 were given`

Is there a workaround you can think of here?

**Comment by matt-dalton** [comment]
Ahh actually, in my case this works if I add in an `args_rewrite=lambda: 'manager_fn'`, which is fine because I want to cache the result globally across a model

**Comment by fjsj** [comment]
I suggest documenting the `method_decorator` trick. Can I open a PR with that?
